# EDA (Exploratory Data Analysis)
## When performing EDA:
1. Use head() and tail() to explore the first and last few rows. This gives us a snapshot of the data's structure.
2. Look for nulls (.isnull.sum()) so we can decide whether to fill gaps, drop them, or handle them some other way.
3. Check the shape (.shape) to see how many rows and columns are in the DataFrame. This can help when merging or transforming data since we can compare what we expect with what actually happens.
4. Look at descriptive stats(.describe()) to get a quick understanding of the numerical data.

#### Importing pandas under the alias pd

In [1]:
import pandas as pd

#### Creating a DataFrame

In [2]:
data = {'Title': ["The Shining", "The Thing", "Rosemary's Baby"], 'Year': [1980, 1982, 1968], 'IMDB Rating': [8.4, 8.2, 8.0]}

movie_df = pd.DataFrame(data)

print(movie_df)

             Title  Year  IMDB Rating
0      The Shining  1980          8.4
1        The Thing  1982          8.2
2  Rosemary's Baby  1968          8.0

#### Viewing the first few rows of a csv DataFrame
Note: I can choose how many rows by passing that number as an argument in the head method

In [3]:
df = pd.read_csv('../data/horror_movies.csv')
df.head()

,id,original_title,title,original_language,overview,tagline,release_date,poster_path,popularity,vote_count,vote_average,budget,revenue,runtime,status,adult,backdrop_path,genre_names,collection,collection_name
0,760161,Orphan: First Kill,Orphan: First Kill,en,After escaping from an Estonian psychiatric fa...,There's always been something wrong with Esther.,2022-07-27,/pHkKbIRoCe7zIFvqan9LFSaQAde.jpg,5088.584,902,6.9,0,9572765,99,Released,False,/5GA3vV1aWWHTSDO5eno8V5zDo8r.jpg,"Horror, Thriller",760193.0,Orphan Collection
1,760741,Beast,Beast,en,A recently widowed man and his two teenage dau...,Fight for family.,2022-08-11,/xIGr7UHsKf0URWmyyd5qFMAq4d8.jpg,2172.338,584,7.1,0,56000000,93,Released,False,/2k9tBql5GYH328Krj66tDT9LtFZ.jpg,"Adventure, Drama, Horror",NaN,NaN
2,882598,Smile,Smile,en,"After witnessing a bizarre, traumatic incident...","Once you see it, it’s too late.",2022-09-23,/hiaeZKzwsk4y4atFhmncO5KRxeT.jpg,1863.628,114,6.8,17000000,45000000,115,Released,False,/mVNPfpydornVe4H4UCIk7WevWjf.jpg,"Horror, Mystery, Thriller",NaN,NaN
3,756999,The Black Phone,The Black Phone,en,"Finney Blake, a shy but clever 13-year-old boy...",Never talk to strangers.,2022-06-22,/lr11mCT85T1JanlgjMuhs9nMht4.jpg,1071.398,2736,7.9,18800000,161000000,103,Released,False,/AfvIjhDu9p64jKcmohS4hsPG95Q.jpg,"Horror, Thriller",NaN,NaN
4,772450,Presencias,Presences,es,A man who loses his wife and goes to seclude h...,NaN,2022-09-07,/dgDT3uol3mdvwEg0jt1ble3l9hw.jpg,1020.995,83,7.0,0,0,0,Released,False,/ojfzhdwRemcDt1I6pao6vVLw9AA.jpg,Horror,NaN,NaN

#### Viewing the last few rows of a DataFrame

In [4]:
df.tail()

,id,original_title,title,original_language,overview,tagline,release_date,poster_path,popularity,vote_count,vote_average,budget,revenue,runtime,status,adult,backdrop_path,genre_names,collection,collection_name
32535,1032201,Catch a Butcher,Catch a Butcher,en,In a maternity ward in nineteenth-century Indi...,NaN,2021-11-20,/4LHrYpe6bjiT8Wvkzl3269LIUZl.jpg,0.6,0,0.0,0,0,11,Released,False,NaN,Horror,NaN,NaN
32536,1032667,Shaye Saint John: The Triggers Compilation,Shaye Saint John: The Triggers Compilation,en,A bizarre mix of early Tod Hayne's and Phyllis...,"""Just keep in mind, that you'll be trying to s...",2006-10-30,/j1vWwxnTsoKjZFwJODiNHNS8GFK.jpg,0.6,0,0.0,0,0,92,Released,False,NaN,"Fantasy, Horror",NaN,NaN
32537,1032890,Welcome to the Occult Forest,Welcome to the Occult Forest,en,A washed up horror film director named Kôji Ku...,"Murders, crimes, laughter, psychics, superhero...",2022-07-22,/ngFyxdliPZrG3Qra7tW3LbWksFd.jpg,0.6,0,0.0,0,0,141,Released,False,/s8Kpai084gCgQlsT3bpaEYuJmDc.jpg,"Comedy, Drama, Horror",NaN,NaN
32538,1033052,The Mean One,The Mean One,en,"The Mean One is a hairy, green-skinned grump i...",NaN,2022-12-15,NaN,0.0,0,0.0,0,0,0,Post Production,False,NaN,Horror,NaN,NaN
32539,1033095,Secret Formula,Secret Formula,en,NaN,NaN,2020-12-06,/5GTTNqHwXfqqnBPrZAv0DVoWfjr.jpg,0.0,0,0.0,0,0,0,Released,False,NaN,"Animation, Horror",NaN,NaN

#### DataFrame summary

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32540 entries, 0 to 32539
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 32540 non-null  int64
 1   original_title     32540 non-null  object
 2   title              32540 non-null  object
 3   original_language  32540 non-null  object
 4   overview           31254 non-null  object
 5   tagline            12706 non-null  object
 6   release_date       32540 non-null  object
 7   poster_path        28066 non-null  object
 8   popularity         32540 non-null  float64
 9   vote_count         32540 non-null  int64
 10  vote_average       32540 non-null  float64
 11  budget             32540 non-null  int64
 12  revenue            32540 non-null  int64
 13  runtime            32540 non-null  int64
 14  status             32540 non-null  object
 15  adult              32540 non-null  bool
 16  backdrop_path      13545 non-null  object
 17  genre_names        32540 non-null  object
 18  collection         2306 non-null   float64
 19  collection_name    2306 non-null   object
dtypes: bool(1), float64(3), int64(5), object(11)
memory usage: 4.7+ MB

#### Getting basic statistics from DataFrame

Benefits:
- Quick snapshot
- Guides further analysis
- Supports data cleaning
- Informs visualization choices

In [6]:
print("Here's the numerical data:")
print(df.describe())

print("\nAnd here's all the data:")
print(df.describe(include='all'))

Here's the numerical data:
                 id    popularity    vote_count  vote_average        budget  \
count  3.254000e+04  32540.000000  32540.000000  32540.000000  3.254000e+04
mean   4.459108e+05      4.013456     62.691487      3.335728  5.431266e+05
std    3.057447e+05     37.513472    420.887474      2.876002  4.542668e+06
min    1.700000e+01      0.000000      0.000000      0.000000  0.000000e+00
25%    1.464948e+05      0.600000      0.000000      0.000000  0.000000e+00
50%    4.265210e+05      0.840000      2.000000      4.000000  0.000000e+00
75%    7.075340e+05      2.243250     11.000000      5.700000  0.000000e+00
max    1.033095e+06   5088.584000  16900.000000     10.000000  2.000000e+08

            revenue       runtime    collection
count  3.254000e+04  32540.000000  2.306000e+03
mean   1.349747e+06     62.142901  4.815349e+05
std    1.443048e+07     40.998527  3.244982e+05
min    0.000000e+00      0.000000  6.560000e+02
25%    0.000000e+00     14.000000  1.554210e+05
50%    0.000000e+00     80.000000  4.712590e+05
75%    0.000000e+00     91.000000  7.590672e+05
max    7.018426e+08    683.000000  1.033032e+06

And here's all the data:
                  id original_title  title original_language  \
count   3.254000e+04          32540  32540             32540
unique           NaN          30296  29563                97
top              NaN           Prey   Prey                en
freq             NaN             11     14             21923
mean    4.459108e+05            NaN    NaN               NaN
std     3.057447e+05            NaN    NaN               NaN
min     1.700000e+01            NaN    NaN               NaN
25%     1.464948e+05            NaN    NaN               NaN
50%     4.265210e+05            NaN    NaN               NaN
75%     7.075340e+05            NaN    NaN               NaN
max     1.033095e+06            NaN    NaN               NaN

                  overview                                          tagline  \
count                31254                                            12706
unique               31020                                            12514
top     No overview found.  Can you face the truth reflected by the camera?
freq                    93                                               13
mean                   NaN                                              NaN
std                    NaN                                              NaN
min                    NaN                                              NaN
25%                    NaN                                              NaN
50%                    NaN                                              NaN
75%                    NaN                                              NaN
max                    NaN                                              NaN

       release_date                       poster_path    popularity  \
count         32540                             28066  32540.000000
unique        10999                             28048           NaN
top      1989-01-01  /r3EnvEwaPHrEcaH7ncbNMrExE3u.jpg           NaN
freq            152                                 3           NaN
mean            NaN                               NaN      4.013456
std             NaN                               NaN     37.513472
min             NaN                               NaN      0.000000
25%             NaN                               NaN      0.600000
50%             NaN                               NaN      0.840000
75%             NaN                               NaN      2.243250
max             NaN                               NaN   5088.584000

          vote_count  vote_average        budget       revenue       runtime  \
count   32540.000000  32540.000000  3.254000e+04  3.254000e+04  32540.000000
unique           NaN           NaN           NaN           NaN           NaN
top              NaN           NaN           NaN           NaN           NaN
freq             NaN           NaN           NaN           NaN           NaN
mean       62.691487      3.335728  5.431266e+05  1.349747e+06     62.142901
std       420.887474      2.876002  4.542668e+06  1.443048e+07     40.998527
min         0.000000      0.000000  0.000000e+00  0.000000e+00      0.000000
25%         0.000000      0.000000  0.000000e+00  0.000000e+00     14.000000
50%         2.000000      4.000000  0.000000e+00  0.000000e+00     80.000000
75%        11.000000      5.700000  0.000000e+00  0.000000e+00     91.000000
max     16900.000000     10.000000  2.000000e+08  7.018426e+08    683.000000

          status  adult                     backdrop_path genre_names  \
count      32540  32540                             13545       32540
unique         4      1                             13536         772
top     Released  False  /6gSPYkvfkBHKL80gTXLBRaEpUDR.jpg      Horror
freq       32405  32540                                 3       12463
mean         NaN    NaN                               NaN         NaN
std          NaN    NaN                               NaN         NaN
min          NaN    NaN                               NaN         NaN
25%          NaN    NaN                               NaN         NaN
50%          NaN    NaN                               NaN         NaN
75%          NaN    NaN                               NaN         NaN
max          NaN    NaN                               NaN         NaN

          collection                collection_name
count   2.306000e+03                           2306
unique           NaN                            815
top              NaN  Honto Ni Atta! Noroi no Video
freq             NaN                             63
mean    4.815349e+05                            NaN
std     3.244982e+05                            NaN
min     6.560000e+02                            NaN
25%     1.554210e+05                            NaN
50%     4.712590e+05                            NaN
75%     7.590672e+05                            NaN
max     1.033032e+06                            NaN

#### Filtering the results from one column of the DataFrame and displaying the first few results
Runtimes over 2 hours (>120 minutes)

In [7]:
filtered_df = df[df['runtime'] > 120]
filtered_df.head()

,id,original_title,title,original_language,overview,tagline,release_date,poster_path,popularity,vote_count,vote_average,budget,revenue,runtime,status,adult,backdrop_path,genre_names,collection,collection_name
7,762504,Nope,Nope,en,Residents in a lonely gulch of inland Californ...,What’s a bad miracle?,2022-07-20,/AcKVlWaNVVVFQwro3nLXqPljcYA.jpg,733.112,1684,7.0,68000000,170800000,130,Released,False,/xVbppM1xgbskOKgOuV8fbWBWHtt.jpg,"Horror, Mystery, Science Fiction, Thriller",NaN,NaN
30,21208,Orphan,Orphan,en,"After losing their baby, a married couple adop...",There's something wrong with Esther.,2009-07-24,/lCGpOgoTOGLtZnBiGY9HRg5Xnjd.jpg,265.858,4403,7.0,20000000,77912251,123,Released,False,/blJVWug8FJggb9gs6NuooyOWBTP.jpg,"Horror, Mystery, Thriller",760193.0,Orphan Collection
41,474350,It Chapter Two,It Chapter Two,en,27 years after overcoming the malevolent super...,You'll Float Again,2019-09-04,/zfE0R94v1E8cuKAerbskfD3VfUt.jpg,230.451,7221,6.9,79000000,473122525,170,Released,False,/8moTOzunF7p40oR5XhlDvJckOSW.jpg,"Fantasy, Horror",477962.0,It Collection
77,259693,The Conjuring 2,The Conjuring 2,en,Lorraine and Ed Warren travel to north London ...,The next true story from the case files of Ed ...,2016-06-08,/zEqyD0SBt6HL7W9JQoWwtd5Do1T.jpg,137.180,7061,7.3,40000000,320392818,134,Released,False,/4mfFtlGeInPrQVm1hpv7th02yjx.jpg,"Horror, Thriller",313086.0,The Conjuring Collection
87,561,Constantine,Constantine,en,John Constantine has literally been to Hell an...,"Hell wants him, Heaven won't take him, Earth n...",2005-02-08,/vPYgvd2MwHlxTamAOjwVQp4qs1W.jpg,119.677,5863,7.0,100000000,230884728,121,Released,False,/tIG8FwHRiHLOlWJdizp2oxdkSL2.jpg,"Action, Fantasy, Horror",1025281.0,Constantine Collection

#### Selecting a few columns from the DataFrame and displaying the first few results

In [8]:
selected_columns = df[['title', 'tagline']]
selected_columns.head()

                title                                           tagline
0  Orphan: First Kill  There's always been something wrong with Esther.
1               Beast                                 Fight for family.
2               Smile                   Once you see it, it’s too late.
3     The Black Phone                          Never talk to strangers.
4           Presences                                               NaN

#### Checking the shape of the DataFrame

In [9]:
df.shape

(32540, 20)

#### Checking DataFrame column names

In [10]:
df.columns

Index(['id', 'original_title', 'title', 'original_language', 'overview',
       'tagline', 'release_date', 'poster_path', 'popularity', 'vote_count',
       'vote_average', 'budget', 'revenue', 'runtime', 'status', 'adult',
       'backdrop_path', 'genre_names', 'collection', 'collection_name'],
      dtype='object')

#### Finding null values

In [11]:
print("null values in the entire DataFrame:")
print(df.isnull().sum())

print("null values in the runtime column:")
print(df['runtime'].isnull().sum())

print("null values in the tagline column:")
print(df['tagline'].isnull().sum())

null values in the entire DataFrame:
id                       0
original_title           0
title                    0
original_language        0
overview              1286
tagline              19834
release_date             0
poster_path           4474
popularity               0
vote_count               0
vote_average             0
budget                   0
revenue                  0
runtime                  0
status                   0
adult                    0
backdrop_path        18995
genre_names              0
collection           30234
collection_name      30234
dtype: int64
null values in the runtime column:
0
null values in the tagline column:
19834

#### Checking data types
Notes:
- bool is a boolean
- datetime is date-based data
- float64 is a float
- int64 is an integer
- object typically indicates text data

In [12]:
df.dtypes

id                     int64
original_title        object
title                 object
original_language     object
overview              object
tagline               object
release_date          object
poster_path           object
popularity           float64
vote_count             int64
vote_average         float64
budget                 int64
revenue                int64
runtime                int64
status                object
adult                   bool
backdrop_path         object
genre_names           object
collection           float64
collection_name       object
dtype: object

#### Converting release_date column type to datetime type

In [13]:
df['release_date'] = pd.to_datetime(df['release_date'])
print(df.dtypes)

id                            int64
original_title               object
title                        object
original_language            object
overview                     object
tagline                      object
release_date         datetime64[ns]
poster_path                  object
popularity                  float64
vote_count                    int64
vote_average                float64
budget                        int64
revenue                       int64
runtime                       int64
status                       object
adult                          bool
backdrop_path                object
genre_names                  object
collection                  float64
collection_name              object
dtype: object

#### Finding the sum of a column

In [14]:
print(df['runtime'].sum())

2022130

#### Finding the mean of a column

In [15]:
df['popularity'].mean()

np.float64(4.013455593116165)

# Cleaning Data

#### Remove missing values when they represent a small, insignificant portion of the dataset or when those records are not essential for analysis.

In [16]:
#Let's take a quick check for null values.
print(df.isnull().sum())
#Let's go ahead and remove rows with null values.
df_cleaned = df.dropna()
print(df_cleaned)
#I can also remove only null rows (or columns) that I want to remove, like 'collections.'
df_cleaned_again = df.dropna(subset=['collection'])
print(df_cleaned_again.head())

id                       0
original_title           0
title                    0
original_language        0
overview              1286
tagline              19834
release_date             0
poster_path           4474
popularity               0
vote_count               0
vote_average             0
budget                   0
revenue                  0
runtime                  0
status                   0
adult                    0
backdrop_path        18995
genre_names              0
collection           30234
collection_name      30234
dtype: int64
           id                                     original_title  \
0      760161                                 Orphan: First Kill
6      717728                           Jeepers Creepers: Reborn
9      760104                                                  X
11     801071                     The Jack in the Box: Awakening
22     610253                                    Halloween Kills
...       ...                                                ...
29749  851499                                   ほんとにあった！呪いのビデオ20
29757  851513                                   ほんとにあった！呪いのビデオ27
30513  890574                              DV5: Cord Cutter Hell
32141  999929            The Beast From Twenty Zillion Years Ago
32142  999943  Night of the Beast (From Twenty Zillion Years ...

                                                   title original_language  \
0                                     Orphan: First Kill                en
6                               Jeepers Creepers: Reborn                en
9                                                      X                en
11                        The Jack in the Box: Awakening                en
22                                       Halloween Kills                en
...                                                  ...               ...
29749              Honto ni Atta! Noroi no Video Vol. 20                ja
29757                   Honto Ni Atta! Noroi No Video 27                ja
30513                              DV5: Cord Cutter Hell                en
32141            The Beast From Twenty Zillion Years Ago                en
32142  Night of the Beast (From Twenty Zillion Years ...                en

                                                overview  \
0      After escaping from an Estonian psychiatric fa...
6      Forced to travel with her boyfriend to a horro...
9      In 1979, a group of young filmmakers set out t...
11     When a vintage Jack-in-the-box is opened by a ...
22     The nightmare isn't over as unstoppable killer...
...                                                  ...
29749  20th entry in the popular "Honto ni Atta. Noro...
29757  27th entry in the popular "Honto ni Atta. Noro...
30513  Two mustachioed cord cutters inadvertently res...
32141  The story of a two-headed dinosaur and his str...
32142  A prehistoric two-headed dinosaur continues it...

                                                 tagline release_date  \
0       There's always been something wrong with Esther.   2022-07-27
6                                       Evil Rides Again   2022-09-15
9                         Dying to show you a good time.   2022-03-17
11         Once you open the box... you can't escape it.   2022-02-24
22                                    Evil dies tonight.   2021-10-14
...                                                  ...          ...
29749  Fear grows! Earthbound spirits, vengeful spiri...   2006-06-02
29757    Can you face the truth reflected by the camera?   2008-02-08
30513                             Death by subscription.   2021-04-10
32141    SHOT ON LOCATION IN THE SHADOW OF 3 MILE ISLAND   2012-07-03
32142                                SHOT IN SLOP-MOTION   2015-12-19

                            poster_path  popularity  vote_count  vote_average  \
0      /pHkKbIRoCe7zIFvqan9LFSaQAde.jpg    5088.584         902           6.9
6      /aGBuiirBIQ7o64FmJxO53eYDuro.jpg     821.605         125           5.8
9      /woTQx9Q4b8aO13jR9dsj8C9JESy.jpg     543.670        1035           6.8
11     /3Ib8vlWTrAKRrTWUrTrZPOMW4jp.jpg     527.579         157           6.4
22     /qmJGd5IfURq8iPQ9KF3les47vFS.jpg     315.027        1941           6.7
...                                 ...         ...         ...           ...
29749  /s4vpTA8VESNdnxW4puCbG7P0BWF.jpg       0.600           0           0.0
29757  /nPbt9490bZMqrbbq7fCEJNCqXDQ.jpg       0.600           0           0.0
30513  /sJoXW4Eg2HKWgwzw7cN8VPWvqiZ.jpg       0.600           0           0.0
32141  /5aKIdOpu7kmyc20ChmTXW483nRt.jpg       0.600           2           9.0
32142  /A8IU899IGacJstUq8daMnlyMWY1.jpg       0.600           2           9.0

         budget    revenue  runtime    status  adult  \
0             0    9572765       99  Released  False
6      20000000    2892594       88  Released  False
9      10000000   14257609      106  Released  False
11            0          0       89  Released  False
22     20000000  131647155      105  Released  False
...         ...        ...      ...       ...    ...
29749         0          0       66  Released  False
29757         0          0       61  Released  False
30513       500          0       53  Released  False
32141         0          0        6  Released  False
32142         0          0        7  Released  False

                          backdrop_path                         genre_names  \
0      /5GA3vV1aWWHTSDO5eno8V5zDo8r.jpg                    Horror, Thriller
6      /tIX6j3NzadlwGcJ52nuWdmtOQkg.jpg           Horror, Mystery, Thriller
9      /21ldFAokKVjwzi1SHXoPb5gc7md.jpg           Horror, Mystery, Thriller
11     /xHRabofjmMGoIV3mb6xgy4nwOcS.jpg                              Horror
22     /5P0PtxIneLNMq7m0crF1R9Sjzpv.jpg                    Horror, Thriller
...                                 ...                                 ...
29749  /oDfpmvljmOj7jS5Hd1Jt0GvirNM.jpg                              Horror
29757  /gTv00C0ASWycN95IA2aalmjy5sz.jpg                              Horror
30513  /s9IrDyXBTzGch8wJ5tMoQknPm24.jpg                              Horror
32141  /q4g7qKN48VzIswCcGeKQZDgbiMQ.jpg  Animation, Horror, Science Fiction
32142  /ouwfnrKptbqjEMveaKfdkBqjBGG.jpg  Animation, Horror, Science Fiction

       collection                                    collection_name
0        760193.0                                  Orphan Collection
6         94899.0                        Jeepers Creepers Collection
9        950289.0                                       X Collection
11       916357.0                         Jack in the Box Collection
22        91361.0                               Halloween Collection
...           ...                                                ...
29749    383032.0                      Honto Ni Atta! Noroi no Video
29757    383032.0                      Honto Ni Atta! Noroi no Video
30513   1014548.0                                      DV collection
32141    999953.0  The Beast From Twenty Zillion Years Ago Collec...
32142    999953.0  The Beast From Twenty Zillion Years Ago Collec...

[1117 rows x 20 columns]
        id                  original_title                           title  \
0   760161              Orphan: First Kill              Orphan: First Kill
6   717728        Jeepers Creepers: Reborn        Jeepers Creepers: Reborn
9   760104                               X                               X
11  801071  The Jack in the Box: Awakening  The Jack in the Box: Awakening
22  610253                 Halloween Kills                 Halloween Kills

   original_language                                           overview  \
0                 en  After escaping from an Estonian psychiatric fa...
6                 en  Forced to travel with her boyfriend to a horro...
9                 en  In 1979, a group of young filmmakers set out t...
11                en  When a vintage Jack-in-the-box is opened by a ...
22                en  The nightmare isn't over as unstoppable killer...

                                             tagline release_date  \
0   There's always been something wrong with Esther.   2022-07-27
6                                   Evil Rides Again   2022-09-15
9                     Dying to show you a good time.   2022-03-17
11     Once you open the box... you can't escape it.   2022-02-24
22                                Evil dies tonight.   2021-10-14

                         poster_path  popularity  vote_count  vote_average  \
0   /pHkKbIRoCe7zIFvqan9LFSaQAde.jpg    5088.584         902           6.9
6   /aGBuiirBIQ7o64FmJxO53eYDuro.jpg     821.605         125           5.8
9   /woTQx9Q4b8aO13jR9dsj8C9JESy.jpg     543.670        1035           6.8
11  /3Ib8vlWTrAKRrTWUrTrZPOMW4jp.jpg     527.579         157           6.4
22  /qmJGd5IfURq8iPQ9KF3les47vFS.jpg     315.027        1941           6.7

      budget    revenue  runtime    status  adult  \
0          0    9572765       99  Released  False
6   20000000    2892594       88  Released  False
9   10000000   14257609      106  Released  False
11         0          0       89  Released  False
22  20000000  131647155      105  Released  False

                       backdrop_path                genre_names  collection  \
0   /5GA3vV1aWWHTSDO5eno8V5zDo8r.jpg           Horror, Thriller    760193.0
6   /tIX6j3NzadlwGcJ52nuWdmtOQkg.jpg  Horror, Mystery, Thriller     94899.0
9   /21ldFAokKVjwzi1SHXoPb5gc7md.jpg  Horror, Mystery, Thriller    950289.0
11  /xHRabofjmMGoIV3mb6xgy4nwOcS.jpg                     Horror    916357.0
22  /5P0PtxIneLNMq7m0crF1R9Sjzpv.jpg           Horror, Thriller     91361.0

                collection_name
0             Orphan Collection
6   Jeepers Creepers Collection
9                  X Collection
11   Jack in the Box Collection
22         Halloween Collection

#### Fill in missing values with a specified value when removing rows is not ideal, and estimates or placeholders can be used.
- Preserves the size of the dataset
- Useful when missing data is not entirely random or when approximate values can be used

In [17]:
df_filled = df.fillna(0) #fills with 0

#Let's see if that eliminated all the nulls.
df_filled.isnull().sum()

#Other filling strategies:
#df_mean_filled = df.fillna(df.mean()) #This doesn't work because you can't fill non-numeric data with numeric data.
df_mean_filled = df.fillna(df.mean(numeric_only=True)) #This solves the problem by filling null values with the mean only when the column is a numeric data type.
df_forward_filled = df.ffill()
df_backward_filled = df.bfill()

#### Transposing rows and columns

In [18]:
transposed_df = df.T

#### Normalizing data

Replacing spaces with undercores in column names

In [19]:
#This isn't necessary for my DataFrame, but I'll put the syntax anyway for reference.
df.columns = df.columns.str.replace(' ', '_')
print(df.columns)

Index(['id', 'original_title', 'title', 'original_language', 'overview',
       'tagline', 'release_date', 'poster_path', 'popularity', 'vote_count',
       'vote_average', 'budget', 'revenue', 'runtime', 'status', 'adult',
       'backdrop_path', 'genre_names', 'collection', 'collection_name'],
      dtype='object')

Converting data to uppercase

In [20]:
#df = df.map(str.upper)
#This gives an error because not all of my objects are strings.

#### Keeping rows that meet a condition (Boolean Indexing)

In [21]:
#New variable only contains rows where runtime is greater than 120

df_filtered = df[df['runtime'] > 120]
print(df_filtered)

            id                original_title                         title  \
7       762504                          Nope                          Nope
30       21208                        Orphan                        Orphan
41      474350                It Chapter Two                It Chapter Two
77      259693               The Conjuring 2               The Conjuring 2
87         561                   Constantine                   Constantine
...        ...                           ...                           ...
32276  1011207                    Evil Lurks                    Evil Lurks
32345  1016519  S.O.V. The True Independents  S.O.V. The True Independents
32347  1016642                     Varnamaya                     Varnamaya
32410  1023241       2 Nights in Soul Valley       2 Nights in Soul Valley
32537  1032890  Welcome to the Occult Forest  Welcome to the Occult Forest

      original_language                                           overview  \
7                    en  Residents in a lonely gulch of inland Californ...
30                   en  After losing their baby, a married couple adop...
41                   en  27 years after overcoming the malevolent super...
77                   en  Lorraine and Ed Warren travel to north London ...
87                   en  John Constantine has literally been to Hell an...
...                 ...                                                ...
32276                en  A troubled woman seeks help from an unscrupulo...
32345                en  Series dedicated to preserving the legacy of s...
32347                kn  A renowned artist's life descends into chaos w...
32410                en                                                NaN
32537                en  A washed up horror film director named Kôji Ku...

                                                 tagline release_date  \
7                                  What’s a bad miracle?   2022-07-20
30                  There's something wrong with Esther.   2009-07-24
41                                    You'll Float Again   2019-09-04
77     The next true story from the case files of Ed ...   2016-06-08
87     Hell wants him, Heaven won't take him, Earth n...   2005-02-08
...                                                  ...          ...
32276                                    Is Anyone Safe?   2022-07-17
32345                                                NaN   2018-11-18
32347  Village is cursed, people have disappeared, so...   2018-11-23
32410                                                NaN   2012-12-28
32537  Murders, crimes, laughter, psychics, superhero...   2022-07-22

                            poster_path  popularity  vote_count  vote_average  \
7      /AcKVlWaNVVVFQwro3nLXqPljcYA.jpg     733.112        1684           7.0
30     /lCGpOgoTOGLtZnBiGY9HRg5Xnjd.jpg     265.858        4403           7.0
41     /zfE0R94v1E8cuKAerbskfD3VfUt.jpg     230.451        7221           6.9
77     /zEqyD0SBt6HL7W9JQoWwtd5Do1T.jpg     137.180        7061           7.3
87     /vPYgvd2MwHlxTamAOjwVQp4qs1W.jpg     119.677        5863           7.0
...                                 ...         ...         ...           ...
32276  /badB2AI9ynlSzA1XeHxcAFDlv2A.jpg       0.600           0           0.0
32345  /kZbzR4NYWlzJduXlKx6epNcFEt7.jpg       0.600           0           0.0
32347  /nVHmLk8DvmtY0O22t2N4bje7veh.jpg       0.600           1           2.0
32410  /thzgu4ujZc9VcsXQ6oEOnBZxdXt.jpg       0.600           0           0.0
32537  /ngFyxdliPZrG3Qra7tW3LbWksFd.jpg       0.600           0           0.0

          budget    revenue  runtime    status  adult  \
7       68000000  170800000      130  Released  False
30      20000000   77912251      123  Released  False
41      79000000  473122525      170  Released  False
77      40000000  320392818      134  Released  False
87     100000000  230884728      121  Released  False
...          ...        ...      ...       ...    ...
32276        150          0      150  Released  False
32345          0          0      140  Released  False
32347     181618          0      130  Released  False
32410          0          0      180  Released  False
32537          0          0      141  Released  False

                          backdrop_path  \
7      /xVbppM1xgbskOKgOuV8fbWBWHtt.jpg
30     /blJVWug8FJggb9gs6NuooyOWBTP.jpg
41     /8moTOzunF7p40oR5XhlDvJckOSW.jpg
77     /4mfFtlGeInPrQVm1hpv7th02yjx.jpg
87     /tIG8FwHRiHLOlWJdizp2oxdkSL2.jpg
...                                 ...
32276                               NaN
32345                               NaN
32347                               NaN
32410                               NaN
32537  /s8Kpai084gCgQlsT3bpaEYuJmDc.jpg

                                      genre_names  collection  \
7      Horror, Mystery, Science Fiction, Thriller         NaN
30                      Horror, Mystery, Thriller    760193.0
41                                Fantasy, Horror    477962.0
77                               Horror, Thriller    313086.0
87                        Action, Fantasy, Horror   1025281.0
...                                           ...         ...
32276                                      Horror         NaN
32345                         Documentary, Horror         NaN
32347                   Horror, Mystery, Thriller         NaN
32410                  Adventure, Horror, Mystery         NaN
32537                       Comedy, Drama, Horror         NaN

                collection_name
7                           NaN
30            Orphan Collection
41                It Collection
77     The Conjuring Collection
87       Constantine Collection
...                         ...
32276                       NaN
32345                       NaN
32347                       NaN
32410                       NaN
32537                       NaN

[786 rows x 20 columns]

#### Removing a column

In [22]:
#New variable does not contain the column 'tagline' from the dataframe 'df'

df_dropped_col = df.drop(columns=['tagline'])
print(df_dropped_col)

            id                              original_title  \
0       760161                          Orphan: First Kill
1       760741                                       Beast
2       882598                                       Smile
3       756999                             The Black Phone
4       772450                                  Presencias
...        ...                                         ...
32535  1032201                             Catch a Butcher
32536  1032667  Shaye Saint John: The Triggers Compilation
32537  1032890                Welcome to the Occult Forest
32538  1033052                                The Mean One
32539  1033095                              Secret Formula

                                            title original_language  \
0                              Orphan: First Kill                en
1                                           Beast                en
2                                           Smile                en
3                                 The Black Phone                en
4                                       Presences                es
...                                           ...               ...
32535                             Catch a Butcher                en
32536  Shaye Saint John: The Triggers Compilation                en
32537                Welcome to the Occult Forest                en
32538                                The Mean One                en
32539                              Secret Formula                en

                                                overview release_date  \
0      After escaping from an Estonian psychiatric fa...   2022-07-27
1      A recently widowed man and his two teenage dau...   2022-08-11
2      After witnessing a bizarre, traumatic incident...   2022-09-23
3      Finney Blake, a shy but clever 13-year-old boy...   2022-06-22
4      A man who loses his wife and goes to seclude h...   2022-09-07
...                                                  ...          ...
32535  In a maternity ward in nineteenth-century Indi...   2021-11-20
32536  A bizarre mix of early Tod Hayne's and Phyllis...   2006-10-30
32537  A washed up horror film director named Kôji Ku...   2022-07-22
32538  The Mean One is a hairy, green-skinned grump i...   2022-12-15
32539                                                NaN   2020-12-06

                            poster_path  popularity  vote_count  vote_average  \
0      /pHkKbIRoCe7zIFvqan9LFSaQAde.jpg    5088.584         902           6.9
1      /xIGr7UHsKf0URWmyyd5qFMAq4d8.jpg    2172.338         584           7.1
2      /hiaeZKzwsk4y4atFhmncO5KRxeT.jpg    1863.628         114           6.8
3      /lr11mCT85T1JanlgjMuhs9nMht4.jpg    1071.398        2736           7.9
4      /dgDT3uol3mdvwEg0jt1ble3l9hw.jpg    1020.995          83           7.0
...                                 ...         ...         ...           ...
32535  /4LHrYpe6bjiT8Wvkzl3269LIUZl.jpg       0.600           0           0.0
32536  /j1vWwxnTsoKjZFwJODiNHNS8GFK.jpg       0.600           0           0.0
32537  /ngFyxdliPZrG3Qra7tW3LbWksFd.jpg       0.600           0           0.0
32538                               NaN       0.000           0           0.0
32539  /5GTTNqHwXfqqnBPrZAv0DVoWfjr.jpg       0.000           0           0.0

         budget    revenue  runtime           status  adult  \
0             0    9572765       99         Released  False
1             0   56000000       93         Released  False
2      17000000   45000000      115         Released  False
3      18800000  161000000      103         Released  False
4             0          0        0         Released  False
...         ...        ...      ...              ...    ...
32535         0          0       11         Released  False
32536         0          0       92         Released  False
32537         0          0      141         Released  False
32538         0          0        0  Post Production  False
32539         0          0        0         Released  False

                          backdrop_path                genre_names  \
0      /5GA3vV1aWWHTSDO5eno8V5zDo8r.jpg           Horror, Thriller
1      /2k9tBql5GYH328Krj66tDT9LtFZ.jpg   Adventure, Drama, Horror
2      /mVNPfpydornVe4H4UCIk7WevWjf.jpg  Horror, Mystery, Thriller
3      /AfvIjhDu9p64jKcmohS4hsPG95Q.jpg           Horror, Thriller
4      /ojfzhdwRemcDt1I6pao6vVLw9AA.jpg                     Horror
...                                 ...                        ...
32535                               NaN                     Horror
32536                               NaN            Fantasy, Horror
32537  /s8Kpai084gCgQlsT3bpaEYuJmDc.jpg      Comedy, Drama, Horror
32538                               NaN                     Horror
32539                               NaN          Animation, Horror

       collection    collection_name
0        760193.0  Orphan Collection
1             NaN                NaN
2             NaN                NaN
3             NaN                NaN
4             NaN                NaN
...           ...                ...
32535         NaN                NaN
32536         NaN                NaN
32537         NaN                NaN
32538         NaN                NaN
32539         NaN                NaN

[32540 rows x 19 columns]

#### Adding a new column based on a condition
- .apply() applies a transformation for each value in the specified column
- lambda x: function checks the Boolean specified

In [23]:
#Creates a new column that labels movies with runtime greater than 120 'Long' and all others 'Short'

df['Length'] = df['runtime'].apply(lambda x: 'Long' if x > 120 else 'Short')
print(df['Length'])

0        Short
1        Short
2        Short
3        Short
4        Short
         ...
32535    Short
32536    Short
32537     Long
32538    Short
32539    Short
Name: Length, Length: 32540, dtype: object

#### Mapping values in a column
- language_mapping = {...} defines a dictionary to map old values to new values
- df['original_language'] selects the column
- .map(language_mapping) looks up each value in the dictionary and replaces it if it exists in the column specified

In [24]:
#Changes 'en' in the 'original_language' column to 'English'

language_mapping = {'en': 'English'}
df['original_language'] = df['original_language'].map(language_mapping)
print(df['original_language'])

0        English
1        English
2        English
3        English
4            NaN
          ...
32535    English
32536    English
32537    English
32538    English
32539    English
Name: original_language, Length: 32540, dtype: object

#### Changing column names
- .rename(columns={}) specifies which columns
- Dictionary keys are the old names
- Dictionary values are the new names

In [25]:
#Creates a new DataFrame where the column 'tagline' is called 'slogan'

df_renamed = df.rename(columns={'tagline' : 'slogan'})
print(df_renamed.head())

       id      original_title               title original_language  \
0  760161  Orphan: First Kill  Orphan: First Kill           English
1  760741               Beast               Beast           English
2  882598               Smile               Smile           English
3  756999     The Black Phone     The Black Phone           English
4  772450          Presencias           Presences               NaN

                                            overview  \
0  After escaping from an Estonian psychiatric fa...
1  A recently widowed man and his two teenage dau...
2  After witnessing a bizarre, traumatic incident...
3  Finney Blake, a shy but clever 13-year-old boy...
4  A man who loses his wife and goes to seclude h...

                                             slogan release_date  \
0  There's always been something wrong with Esther.   2022-07-27
1                                 Fight for family.   2022-08-11
2                   Once you see it, it’s too late.   2022-09-23
3                          Never talk to strangers.   2022-06-22
4                                               NaN   2022-09-07

                        poster_path  popularity  vote_count  ...    budget  \
0  /pHkKbIRoCe7zIFvqan9LFSaQAde.jpg    5088.584         902  ...         0
1  /xIGr7UHsKf0URWmyyd5qFMAq4d8.jpg    2172.338         584  ...         0
2  /hiaeZKzwsk4y4atFhmncO5KRxeT.jpg    1863.628         114  ...  17000000
3  /lr11mCT85T1JanlgjMuhs9nMht4.jpg    1071.398        2736  ...  18800000
4  /dgDT3uol3mdvwEg0jt1ble3l9hw.jpg    1020.995          83  ...         0

     revenue  runtime    status  adult                     backdrop_path  \
0    9572765       99  Released  False  /5GA3vV1aWWHTSDO5eno8V5zDo8r.jpg
1   56000000       93  Released  False  /2k9tBql5GYH328Krj66tDT9LtFZ.jpg
2   45000000      115  Released  False  /mVNPfpydornVe4H4UCIk7WevWjf.jpg
3  161000000      103  Released  False  /AfvIjhDu9p64jKcmohS4hsPG95Q.jpg
4          0        0  Released  False  /ojfzhdwRemcDt1I6pao6vVLw9AA.jpg

                 genre_names collection    collection_name Length
0           Horror, Thriller   760193.0  Orphan Collection  Short
1   Adventure, Drama, Horror        NaN                NaN  Short
2  Horror, Mystery, Thriller        NaN                NaN  Short
3           Horror, Thriller        NaN                NaN  Short
4                     Horror        NaN                NaN  Short

[5 rows x 21 columns]

#### Creating a column

Note: This (a vectorized operation) is faster than using .apply() with a function

In [26]:
#Creates a new column where the runtime is calculated in hours instead of minutes

df['runtime_hours'] = df['runtime'] / 60

print(df.head(1))

       id      original_title               title original_language  \
0  760161  Orphan: First Kill  Orphan: First Kill           English

                                            overview  \
0  After escaping from an Estonian psychiatric fa...

                                            tagline release_date  \
0  There's always been something wrong with Esther.   2022-07-27

                        poster_path  popularity  vote_count  ...  revenue  \
0  /pHkKbIRoCe7zIFvqan9LFSaQAde.jpg    5088.584         902  ...  9572765

   runtime    status  adult                     backdrop_path  \
0       99  Released  False  /5GA3vV1aWWHTSDO5eno8V5zDo8r.jpg

        genre_names collection    collection_name  Length runtime_hours
0  Horror, Thriller   760193.0  Orphan Collection   Short          1.65

[1 rows x 22 columns]

# Data Wrangling

#### Aggregating Data  
.agg() let's you:  
- Apply multiple summary statistics (e.g., sum, mean, max, min, count, etc.).
- Apply different aggregations to different columns.

In [30]:
#Reminding myself which columns I have to work with
df.columns

Index(['id', 'original_title', 'title', 'original_language', 'overview',
       'tagline', 'release_date', 'poster_path', 'popularity', 'vote_count',
       'vote_average', 'budget', 'revenue', 'runtime', 'status', 'adult',
       'backdrop_path', 'genre_names', 'collection', 'collection_name',
       'Length', 'runtime_hours'],
      dtype='object')

In [31]:
#Let's find the minimum, maximum, and mean runtimes as well as the minimum, maximum, and mean budget.
df.agg({'runtime' : ['min', 'max', 'mean'], 'budget': ['min', 'max', 'mean']})

         runtime        budget
min     0.000000  0.000000e+00
max   683.000000  2.000000e+08
mean   62.142901  5.431266e+05

#### Grouping Data
.groupby() divides data into groups based on a column in order to perform a function (e.g., sum, mean, etc.) on each group and return the results in a new DataFrame or Series.

In [32]:
#We can group the movies by genre_names and look at the total movies listed for each.

movie_genres = df.groupby('genre_names')[['title']].count() #Counts the number of entries while .sum() would have added them, which would have been inappropriate for strings.

movie_genres

                                                    title
genre_names
Action, Adventure, Animation, Comedy, Drama, Fa...      1
Action, Adventure, Animation, Comedy, Fantasy, ...      1
Action, Adventure, Animation, Comedy, Horror            1
Action, Adventure, Animation, Drama, Fantasy, H...      1
Action, Adventure, Animation, Family, Fantasy, ...      1
...                                                   ...
Horror, Thriller, War                                   8
Horror, Thriller, Western                               9
Horror, War                                            18
Horror, Western                                        49
Thriller                                                1

[772 rows x 1 columns]

#### Resetting the index  
When you alter a DataFrame, the index may no longer make sense, so you must remember to reset it.

In [33]:
#The new variable 'movie_ratings' can get a brand new index, for example.

movie_genres.reset_index()

                                           genre_names  title
0    Action, Adventure, Animation, Comedy, Drama, F...      1
1    Action, Adventure, Animation, Comedy, Fantasy,...      1
2         Action, Adventure, Animation, Comedy, Horror      1
3    Action, Adventure, Animation, Drama, Fantasy, ...      1
4    Action, Adventure, Animation, Family, Fantasy,...      1
..                                                 ...    ...
767                              Horror, Thriller, War      8
768                          Horror, Thriller, Western      9
769                                        Horror, War     18
770                                    Horror, Western     49
771                                           Thriller      1

[772 rows x 2 columns]

### Functions!
We can use functions to group code together into something that can:  
- Generate a report using different data.
- Be imported into other files

In [34]:
#Defining a function to report on aggregated movie data.

def genre_counts(df):
    movie_genres = df.groupby('genre_names')[['title']].count()
    movie_genres.reset_index()
    print(f"Here are the number of horror movies that fall under each genre:\n{movie_genres}")
    return genre_counts 

genre_counts(df)

Here are the number of horror movies that fall under each genre:
                                                    title
genre_names
Action, Adventure, Animation, Comedy, Drama, Fa...      1
Action, Adventure, Animation, Comedy, Fantasy, ...      1
Action, Adventure, Animation, Comedy, Horror            1
Action, Adventure, Animation, Drama, Fantasy, H...      1
Action, Adventure, Animation, Family, Fantasy, ...      1
...                                                   ...
Horror, Thriller, War                                   8
Horror, Thriller, Western                               9
Horror, War                                            18
Horror, Western                                        49
Thriller                                                1

[772 rows x 1 columns]